-- Run this in Supabase SQL editor to enable monetization event storage.
-- It powers /api/event ingestion and the Admin revenue signals dashboard.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  template_type text null,
  path text null,
  referrer text null,
  brand_slug text null,
  brand_name text null,
  cta_type text null,
  ad_slot text null,
  ad_label text null,
  affiliate_provider text null,
  report_type text null,
  method text null,
  brand_is_open boolean null,
  content_type text null,
  ip_hash text null,
  user_agent text null,
  metadata jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_template_idx
  on public.analytics_events (template_type, created_at desc);

create index if not exists analytics_events_path_idx
  on public.analytics_events (path);

alter table public.analytics_events enable row level security;

-- Read-only access for anon is intentionally disabled.
revoke all on public.analytics_events from anon;
revoke all on public.analytics_events from authenticated;
